language: python
python:
  - 2.7
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - pip install nose
  - pip install numpy
  - pip freeze
install:
  - python setup.py install
script:
  - nosetests